title: AutomationHomeX
description: Automatizacija, razvoj i moji projekti.
url: "https://automationhomex.github.io"
baseurl: ""
theme: just-the-docs
exclude:
  - automate/
# Dodaj ovo u _config.yml
sass:
  style: compressed